receivers:
  mqtt:
    broker: ${env:MQTT_BROKER:-tcp://127.0.0.1:1883}
    topics: ["${env:MQTT_TOPIC}"]
    username: ${env:MQTT_USERNAME}
    password: ${env:MQTT_PASSWORD}

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [mqtt]
      exporters: [debug]
