// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("mqtt")
	ScopeName = "github.com/abicky/opentelemetry-collector-mqtt/receiver/mqttreceiver"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
